### ISSUE TITLE
検索機能のマッチをタイトルのみにする

### ISSUE THREAD

**Issue by somebodyN** [mnao305/mai-score#146]
## リクエストする機能の説明
現状の検索方法だと、選択されている全てのカラムに対して検索が行われるので、「Master」などど検索をすると、難易度カラムの「Master」にマッチして全ての曲のMasterが表示される。
そこはフィルタ機能で制御されているはずなので、検索でサーチされるのをタイトルのみにするのはどうですか。

**Comment by mnao305** [comment]
ここら辺の関数をいじればできそうかな。
https://github.com/mnao305/mai-score/blob/develop/client/components/ScoreTable.vue#L427-L434
